-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 10:02:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema artshopdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema artshopdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artshopdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `artshopdb` ;

-- -----------------------------------------------------
-- Table `artshopdb`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artshopdb`.`cart` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `userId` BIGINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_cart_user` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_cart_user`
    FOREIGN KEY (`userId`)
    REFERENCES `artshopdb`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artshopdb`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artshopdb`.`cart_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cartId` BIGINT NOT NULL,
  `productId` BIGINT NOT NULL,
  `quantity` SMALLINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_cartId_productId` (`cartId` ASC, `productId` ASC) VISIBLE,
  INDEX `idx_cart_item_cart` (`cartId` ASC) VISIBLE,
  INDEX `idx_cart_item_product` (`productId` ASC) VISIBLE,
  CONSTRAINT `fk_cart_item_cart`
    FOREIGN KEY (`cartId`)
    REFERENCES `artshopdb`.`cart` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_cart_item_product`
    FOREIGN KEY (`productId`)
    REFERENCES `artshopdb`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artshopdb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artshopdb`.`category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `imageName` VARCHAR(35) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artshopdb`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artshopdb`.`order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `orderId` BIGINT NOT NULL,
  `productId` BIGINT NOT NULL,
  `price` FLOAT NOT NULL,
  `discount` FLOAT NOT NULL,
  `quantity` SMALLINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_order_item_orders` (`orderId` ASC) VISIBLE,
  INDEX `idx_order_item_product` (`productId` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_orders`
    FOREIGN KEY (`orderId`)
    REFERENCES `artshopdb`.`orders` (`id`),
  CONSTRAINT `fk_order_item_product`
    FOREIGN KEY (`productId`)
    REFERENCES `artshopdb`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artshopdb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artshopdb`.`orders` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `userId` BIGINT NOT NULL,
  `status` TINYINT NOT NULL,
  `deliveryMethod` TINYINT NOT NULL,
  `deliveryPrice` FLOAT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_orders_user` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_orders_user`
    FOREIGN KEY (`userId`)
    REFERENCES `artshopdb`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artshopdb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artshopdb`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `discount` FLOAT NOT NULL,
  `quantity` SMALLINT NOT NULL,
  `totalBuy` SMALLINT NOT NULL,
  `author` VARCHAR(50) NOT NULL,
  `size` VARCHAR(100) NOT NULL,
  `publisher` VARCHAR(100) NOT NULL,
  `yearPublishing` INT NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `imageName` VARCHAR(35) NULL DEFAULT NULL,
  `shop` BIT(1) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  `startsAt` DATETIME NULL DEFAULT NULL,
  `endsAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artshopdb`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artshopdb`.`product_category` (
  `productId` BIGINT NOT NULL,
  `categoryId` BIGINT NOT NULL,
  PRIMARY KEY (`productId`, `categoryId`),
  INDEX `idx_product_category_product` (`productId` ASC) VISIBLE,
  INDEX `idx_product_category_category` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_product_category_category`
    FOREIGN KEY (`categoryId`)
    REFERENCES `artshopdb`.`category` (`id`),
  CONSTRAINT `fk_product_category_product`
    FOREIGN KEY (`productId`)
    REFERENCES `artshopdb`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artshopdb`.`product_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artshopdb`.`product_review` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `userId` BIGINT NOT NULL,
  `productId` BIGINT NOT NULL,
  `ratingScore` TINYINT NOT NULL,
  `content` TEXT NOT NULL,
  `isShow` BIT(1) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_product_review_user` (`userId` ASC) VISIBLE,
  INDEX `idx_product_review_product` (`productId` ASC) VISIBLE,
  CONSTRAINT `fk_product_review_product`
    FOREIGN KEY (`productId`)
    REFERENCES `artshopdb`.`product` (`id`),
  CONSTRAINT `fk_product_review_user`
    FOREIGN KEY (`userId`)
    REFERENCES `artshopdb`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artshopdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artshopdb`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `fullname` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phoneNumber` VARCHAR(11) NOT NULL,
  `gender` BIT(1) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `role` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `uq_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `uq_phoneNumber` (`phoneNumber` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artshopdb`.`wishlist_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artshopdb`.`wishlist_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `userId` BIGINT NOT NULL,
  `productId` BIGINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_userId_productId` (`userId` ASC, `productId` ASC) VISIBLE,
  INDEX `idx_wishlist_item_user` (`userId` ASC) VISIBLE,
  INDEX `idx_wishlist_item_product` (`productId` ASC) VISIBLE,
  CONSTRAINT `fk_wishlist_item_product`
    FOREIGN KEY (`productId`)
    REFERENCES `artshopdb`.`product` (`id`),
  CONSTRAINT `fk_wishlist_item_user`
    FOREIGN KEY (`userId`)
    REFERENCES `artshopdb`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
